import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { FormattedMessage } from "react-intl"
import Newsletter from "../components/Newsletter"
import ToggleSwitch from "../components/toggleSwitch"
import CenterLogo from "../components/centerLogo"
import SocialNetworks from "../components/SocialNetworks"
import CookieConsent from "react-cookie-consent"
import Whitelist from "../components/Whithelist"

export default function Home() {
    return (
        <div className="flex justify-center min-h-screen bg-gradient-to-r from-[#cbd5e1] via-[#f8fafc] to-[#cbd5e1]">
            <Head>
                <title>KUBICS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid content-between w-11/12 min-h-screen max-w-screen-3xl">
                <header className="flex justify-end">
                    {/* Switch to  change language */}
                    <ToggleSwitch />
                </header>
                <main className="flex flex-col items-center pb-8">
                    <h3 className="text-2xl text-center">
                        <FormattedMessage
                            id="app.slogan"
                            defaultMessage="The world will never be round again"
                        />
                    </h3>

                    {/* Kubics Logo */}
                    <div className="mt-6 mb-2 md:mt-14">
                        <CenterLogo />
                    </div>

                    {/* Sentences */}
                    <div className="justify-center hidden mb-4 md:flex">
                        <div className="  text-center pb-5 pt-2 border-t  border-[#7094b1] ">
                            <FormattedMessage
                                id="app.text1"
                                defaultMessage="the NFT Project that will change the course of Filmmaking History"
                            />
                        </div>
                    </div>
                    {/* For Mobile */}
                    <div className="text-center md:hidden">
                        <div className="mb-5 p-1  border-t  border-[#7094b1] ">
                            <FormattedMessage
                                id="app.text1"
                                defaultMessage="the NFT Project that will change the course of Filmmaking History"
                            />
                        </div>
                    </div>
                    {/* WalletConnect */}
                    <div className="flex justify-center 3">
                        <Whitelist />
                    </div>
                </main>

                <footer className="flex flex-col items-center justify-center">

                    {/* Newsletter */}
                    <div className="flex w-4/12 justify- ">
                        <Newsletter />
                    </div>
                    <div className="flex flex-row items-center justify-center w-3/5 text-center ">
                        <FormattedMessage id="app.text2" defaultMessage="More info" />
                        <SocialNetworks />
                    </div>


                    <CookieConsent
                        location="bottom"
                        buttonText="Accept"
                        declineButtonText="Reject"
                        enableDeclineButton
                        onDecline={() => {
                            alert("Not accepted!")
                        }}
                        cookieName="myAwesomeCookieName2"
                        style={{ background: "#2B373B" }}
                        buttonStyle={{ color: "#4e503b", fontSize: "13px" }}
                        declineButtonStyle={{ color: "#4e503b", background: "#918f8e" }}
                        expires={150}
                    >
                        This website uses cookies to enhance the user experience.
                    </CookieConsent>
                </footer>
            </div>
        </div>
    )
}
